### ISSUE TITLE
Syntax errors cause gulp to exit

### ISSUE THREAD

**Issue by joewhite** [guzart/gulp-typescript-compiler#3]
I've set up a gulpfile with gulp.watch, but if one of the watched TypeScript files has a syntax error, the gulp-typescript-compiler task exits gulp completely with an unhandled exception. It should report the error and continue watching.

My gulp task:

```
var gulp = require('gulp');
var gutil = require('gulp-util');
var tsc = require('gulp-typescript-compiler');
gulp.task('ts', function() {
  return gulp
    .src('src/**/*.ts')
    .pipe(tsc())
    .pipe(gulp.dest('dist/js'))
    .on('error', gutil.log);
});
gulp.task('watch', function() {
  gulp.watch(paths.ts, ['ts']);
});
```

I've tried it both with and without the `.on('error', gutil.log)` and the results are the same either way.

I start the watch task, and then paste this code into a TypeScript file. (I'm still learning TypeScript, so yes, the `function` inside the `class` is wrong and a syntax error. But it should report an error in gulp, not crash out with an unhandled exception.)

```
class A {
  function b() {}
}
```

Here's the resulting error output:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'logErrors' of undefined
    at C:\dev\myapp\node_modules\gulp-typescript-compiler\index.js:54:32
    at Array.forEach (native)
    at C:\dev\myapp\node_modules\gulp-typescript-compiler\index.js:53:29
    at Array.forEach (native)
    at Transform.objectStream [as _transform] (C:\dev\myapp\node_modules\gulp-typescript-compiler\index.js:49:24)
    at Transform._read (C:\dev\myapp\node_modules\gulp-typescript-compiler\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Transform._write (C:\dev\myapp\node_modules\gulp-typescript-compiler\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\dev\myapp\node_modules\gulp-typescript-compiler\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:238:10)
    at writeOrBuffer (C:\dev\myapp\node_modules\gulp-typescript-compiler\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:228:5)
    at Transform.Writable.write (C:\dev\myapp\node_modules\gulp-typescript-compiler\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:195:11)
    at write (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:605:24)
    at flow (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:614:7)
    at Transform.pipeOnReadable (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:646:5)
    at Transform.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:430:10)
    at emitReadable (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:426:5)
    at readableAddChunk (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:187:9)
    at Transform.Readable.push (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:149:10)
    at Transform.push (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:145:32)
    at afterTransform (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:101:12)
    at TransformState.afterTransform (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at Transform.noop [as _transform] (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\through2.js:8:3)
    at Transform._read (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at Transform._write (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:238:10)
    at writeOrBuffer (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:228:5)
    at Transform.Writable.write (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:195:11)
    at write (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:605:24)
    at flow (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:614:7)
    at Transform.pipeOnReadable (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:646:5)
    at Transform.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:430:10)
    at emitReadable (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:426:5)
    at readableAddChunk (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:187:9)
    at Transform.Readable.push (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:149:10)
    at Transform.push (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:145:32)
    at afterTransform (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:101:12)
    at TransformState.afterTransform (C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\lib\src\getContents\bufferFile.js:12:5
    at evalmachine.<anonymous>:266:14
    at C:\dev\myapp\node_modules\gulp\node_modules\vinyl-fs\node_modules\graceful-fs\graceful-fs.js:102:5
    at Object.oncomplete (evalmachine.<anonymous>:107:15)
```

**Comment by joewhite** [comment]
Oops, my bad. Closing as test case error. The `.on('error', gutil.log)` needs to go immediately after `.pipe(tsc())`, and then everything is fine.
